name: e621
description: A client library for the API of imageboard using e621 fork of gelbooru.
version: 1.1.0
repository: https://github.com/shalien/e621

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  http: ^1.2.0
  http_parser: ^4.0.2
  meta: ^1.12.0

dev_dependencies:
  lints: ^4.0.0
  pana: ^0.22.2
  test: ^1.25.2
